FROM php:8.2-rc-apache

RUN docker-php-ext-install mysqli && \
  mv "$PHP_INI_DIR/php.ini-production" "$PHP_INI_DIR/php.ini" && \
  mkdir /var/www/phpinfo && \
  a2enmod rewrite && \
  echo "<?php\nphpinfo();" > /var/www/phpinfo/phpinfo.php && \
  echo 'Alias "/phpinfo" "/var/www/phpinfo/phpinfo.php"' > /etc/apache2/conf-enabled/phpinfo.conf

COPY php-mtt.ini     /usr/local/etc/php/conf.d/
COPY php-opcache.ini /usr/local/etc/php/conf.d/
