FROM php:8.1-apache

RUN docker-php-ext-install mysqli && \
  mv "$PHP_INI_DIR/php.ini-production" "$PHP_INI_DIR/php.ini" && \
  mkdir /var/www/phpinfo && \
  echo "<?php\nphpinfo();" > /var/www/phpinfo/phpinfo.php && \
  echo 'Alias "/phpinfo" "/var/www/phpinfo/phpinfo.php"' > /etc/apache2/conf-enabled/phpinfo.conf && \
  a2enmod rewrite && \
  echo 'LogFormat "%h %l %u %t \"%r\" %>s %O \"%{Referer}i\"" combined' > /etc/apache2/conf-enabled/logformat.conf && \
  curl -o /usr/local/bin/phpunit -fL "https://phar.phpunit.de/phpunit-9.phar" && \
  chmod +x /usr/local/bin/phpunit && \
  ln -s html /var/www/src


COPY php-mtt.ini     /usr/local/etc/php/conf.d/
COPY php-opcache.ini /usr/local/etc/php/conf.d/
